name: weather
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^2.3.14
  supabase: ^0.3.5
  supabase_flutter: ^0.3.1+3
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  postgrest: ^0.1.11
  stacked_services: ^0.9.3
  stacked_hooks: ^0.2.2
  stacked_themes: ^0.3.9
  logger: ^1.1.0
  google_fonts: ^3.0.1
  form_validator: ^1.0.2
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  expandable_text: ^2.3.0
  flutter_image_slideshow: ^0.1.2
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner:
  stacked_generator:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/